version: '3'
services:
  app:
    build: .
    ports:
      - 8000:8000
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=gneft_user
      - POSTGRES_PASSWORD=gneft_password
      - POSTGRES_DB=gneft_db  